version = 0.1

[default.deploy.parameters]
stack_name = "ByteMentor"
resolve_s3 = true
s3_prefix = "ByteMentor"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "BedrockRegion=\"us-east-1\" SESEmailSender=\"ab408408@gmail.com\" SESEmailRecipient=\"ab408408@gmail.com\""
disable_rollback = true

[default.global.parameters]
region = "us-east-1"
